version: "2"
run:
  issues-exit-code: 1
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - gosmopolitan
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - whitespace
    - zerologlint
    - govet
    - ineffassign
    - unused
  settings:
    recvcheck:
      disable-builtin: true
      exclusions:
        - "*.String"
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          deny:
            - pkg: reflect
              desc: Reflection is never clear.
            - pkg: gob
              desc: Please convert types manually
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    goconst:
      min-len: 3
      min-occurrences: 5
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    lll:
      tab-width: 1
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-no-explanation: ['gosec']
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
    varnamelen:
      min-name-length: 2
  exclusions:
    generated: lax
    rules:
      - linters:
          - copyloopvar
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - maintidx
          - unparam
        path: _test(ing)?\.go
      - linters:
          - dupl
        path: _conversion\.go
      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)
      - linters:
          - gocritic
        text: '(hugeParam|rangeValCopy):'
      - linters:
          - staticcheck
        text: 'SA3000:'
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G104:'
      - linters:
          - gosec
        text: 'G404:'
    paths:
      - cmd/tmp/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
